# Generated by Django 4.1.4 on 2023-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ф.И.О.')),
                ('specialization', models.CharField(choices=[('Воспитатель', 'Воспитатель'), ('Помощник воспитателя', 'Помощник воспитателя'), ('Педагог доп. образования', 'Педагог доп. образования'), ('Спец', 'Спец')], max_length=50, verbose_name='Специальность')),
                ('education', models.CharField(choices=[('Основное общее', 'Основное общее'), ('Среднее общее', 'Среднее общее'), ('Среднее проф.', 'Среднее проф.'), ('Высшее', 'Высшее')], max_length=50, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
                ('quote', models.CharField(max_length=100, verbose_name='Цитата')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
            },
        ),
    ]
