# Generated by Django 4.1.4 on 2023-06-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Педагог', 'Педагог'), ('Родитель', 'Родитель')], default='Педагог', max_length=8, verbose_name='Образование'),
            preserve_default=False,
        ),
    ]
