# Generated by Django 4.1.4 on 2023-06-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Педагог', 'Педагог'), ('Родитель', 'Родитель')], default='Родитель', max_length=8, verbose_name='Образование'),
        ),
    ]
