# Generated by Django 4.1.4 on 2023-06-18 07:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ф.И.О. ребёнка')),
                ('bdd', models.DateField(verbose_name='Дата рождения')),
                ('parent_full_name', models.CharField(max_length=50, verbose_name='Ф.И.О. родителя(ей)')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона родителя/опекуна')),
                ('art_club', models.BooleanField(verbose_name='Юный художник (Рисование)')),
                ('dance_club', models.BooleanField(verbose_name='Танцуем вместе (Танцы)')),
                ('music', models.BooleanField(verbose_name='Весёлые нотки (Музыкальный кружок)')),
                ('physical_culture_club', models.BooleanField(verbose_name='Спортивные ребята (Физкультурный кружок)')),
                ('needlework_club', models.BooleanField(verbose_name='Волшебные ручки (Рукоделие)')),
                ('robotics', models.BooleanField(verbose_name='Ротоботехника')),
                ('foreign_languages', models.BooleanField(verbose_name='Английский язык')),
                ('orientation_of_education', models.CharField(choices=[('ОБЖ', 'Основы безопасности жизнедеятельности'), ('НПВ', 'Нравствено-патриотическое воспитание'), ('КЭН', 'Культурно-этические нормы'), ('ВФК', 'Воспитание финансовой культуры'), ('ЭВ', 'Экологическое воспитание'), ('ИЗ', 'Индивидуальное развитие'), ('РР', 'Развитие речи'), ('МО', 'Методика общения'), ('ХЭР', 'Художествено-эстетическое развитие'), ('МРВ', 'Музыкально-ритмическое воспитание'), ('ФВ', 'Физическое воспитание'), ('РКРТ', 'Развитие конструирования и ручного труда')], max_length=4, verbose_name='Направленость обучения')),
                ('specialist_service', models.CharField(choices=[('ЛД', 'Логопед-дефектолог'), ('С', 'Сурдопедагог (Нарушение слуха)'), ('Т', 'Тифлопедагог (Нарушение зрения)')], max_length=2, verbose_name='Услуги специалиста')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
