# Generated by Django 4.1.4 on 2023-06-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_parent_child_teacher_child_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
    ]
