# Generated by Django 4.1.4 on 2023-06-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherApplication',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Заявки на трудоустройство'},
        ),
    ]
