# Generated by Django 4.1.4 on 2023-06-17 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_delete_teacherapplication_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ваше Ф.И.О.')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('education', models.CharField(choices=[('Основное общее', 'Основное общее'), ('Среднее общее', 'Среднее общее'), ('Среднее проф.', 'Среднее проф.'), ('Высшее', 'Высшее')], max_length=50, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
                ('specialization', models.CharField(choices=[('Воспитатель', 'Воспитатель'), ('Помощник воспитателя', 'Помощник воспитателя'), ('Педагог доп. образования', 'Педагог доп. образования'), ('Специалист', 'Специалист'), ('Другое', 'Другое')], max_length=50, verbose_name='Специальность')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Заявка на трудоустройство',
                'verbose_name_plural': 'Заявки на трудоустройство',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
