# Generated by Django 4.1.4 on 2023-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_childapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='specialist_service',
            field=models.CharField(choices=[('ЛД', 'Логопед-дефектолог'), ('С', 'Сурдопедагог (Нарушение слуха)'), ('Т', 'Тифлопедагог (Нарушение зрения)')], max_length=2, verbose_name='Услуги специалиста'),
        ),
    ]
